### ISSUE TITLE
Geneva's stable-coin (xsd / aave)

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/aave-v3-interface#19]
- [x] aave-v3-interface added token and mint
- [x] aave-v3-deploy deploy all contracts
- [x] aave-v3-interface config change
- [x] rename domain to [geneva-xsd.moonchain.com](https://geneva-xsd.moonchain.com/)

**Comment by hairyf** [comment]
[ ] aave-v3-interface added token and mint

**Comment by hairyf** [comment]
related to https://github.com/MXCzkEVM/MEP-1759-DApp-store/issues/36 association

**Comment by SanghamitraBhowmick1993** [comment]
1. The logo representing Moonchain needs to be updated.

![Image](https://github.com/MXCzkEVM/aave-v3-interface/assets/93600163/bef470c0-67be-462b-a530-5cade52e002b)

**Comment by hairyf** [comment]
do not use the sign message mode, as this will result in the inability to execute

**Comment by SanghamitraBhowmick1993** [comment]
Add to wallet is not working

![Image](https://github.com/MXCzkEVM/aave-v3-interface/assets/93600163/0cbcd4f7-bcad-430a-a3ca-6a9797043331)

**Comment by SanghamitraBhowmick1993** [comment]
The issues in this tickets is addressed and working as expected. have logged the last issue here https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=60378384, hence moving this ticket to done
