### ISSUE TITLE
Mainnet Chain Header Displayed on Geneva XSD URL

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/aave-v3-interface#20]
When attempting to access the Geneva XSD URL, I noticed that the header indicates the mainnet chain. Additionally, when trying to perform any actions, it prompts me to switch the chain to mainnet.

![Image](https://github.com/MXCzkEVM/aave-v3-interface/assets/93600163/67c09ed6-4d06-4e0b-9459-dab80e953b88)

**Comment by SanghamitraBhowmick1993** [comment]
This is working 

![Image](https://github.com/MXCzkEVM/aave-v3-interface/assets/93600163/3eb0219a-32c7-4f29-8999-667a773ae0c7)
